image:
  repository: "test"
  tag: "test"
  tunnelClientTag: ""
  registrykey: ""

config:
  tunnel:
    serverHost: ""
    authToken: ""
    dataPlaneId: ""
    k8sToken: ""
    tunnelHost: ""
    ssl: true