apiVersion: v1
{{- if ne .Values.image.registrykey "" }}
imagePullSecrets:
- name: registrykey
{{- end }}
kind: ServiceAccount
metadata:
  name: cloud-agent-sa
  namespace: vdc
  annotations:
    app: cloud-agent